### ISSUE TITLE
Questions about data

### ISSUE THREAD

**Issue by lzql1zq** [RManLuo/MotifGNN#1]
Hello, the link to publish data is invalid, can you upload data again? Thank you very much!

**Comment by RManLuo** [comment]
Hi, the link has been updated at [here](https://drive.google.com/file/d/1u-59m0u5-pcF4TCN6zjGLICWFdQteCUG/view?usp=sharing).

**Comment by lzql1zq** [comment]
Thank you very much!&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Linhao Luo ***@***.***&gt;; 
发送时间: 2022年6月14日(星期二) 中午11:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [RManLuo/MotifGNN] Questions about data (Issue #1)





 
Hi, the link has been updated at here.

**Comment by lzql1zq** [comment]
您好，我在运行您这篇论文的源码的时候发现缺少uid_2_idx.pkl和recommend_M1+M4_b_2.pth这两个文件，请问您方便给我源码运行所必须的数据文件吗？非常感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Linhao Luo ***@***.***&gt;; 
发送时间: 2022年6月14日(星期二) 中午11:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [RManLuo/MotifGNN] Questions about data (Issue #1)





 
Closed #1 as completed.

**Comment by RManLuo** [comment]
For the uid_2_idx.pkl, you can uncomment the lines below, and run data_preprocess.py to generate the required files.https://github.com/RManLuo/MotifGNN/blob/b23c8275c87c1250a5cb2cccdcc117cd440e8988/src_sjjy/data_preprocess.py#L109-L111

The recommend_M1+M4_b_2.pth is the final model checkpoint. You can run train_pipline.py to generate ti.

**Comment by lzql1zq** [comment]
OK, Thank you very much！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Linhao Luo ***@***.***&gt;; 
发送时间: 2022年6月16日(星期四) 上午9:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [RManLuo/MotifGNN] Questions about data (Issue #1)





 
For the uid_2_idx.pkl, you can uncomment the lines below, and run data_preprocess.py to generate the required files.https://github.com/RManLuo/MotifGNN/blob/b23c8275c87c1250a5cb2cccdcc117cd440e8988/src_sjjy/data_preprocess.py#L109-L111
 
The recommend_M1+M4_b_2.pth is the final model checkpoint. You can run train_pipline.py to generate ti.
